###
# #%L
# MuleSoft Training - Anypoint Platform Development: Level 2
# %%
# Copyright (C) 2019 - 2021 MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
# %%
# The software in this package is published under the terms of the
# Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License,
# a copy of which has been included with this distribution in the LICENSE.txt file.
# #L%
###
# Autodiscovery API ID in API Manager in this environment
api:
  id: "15617772"

tls.keystore:
  type:  "pkcs12"
  path:  "certs/${project.name}.p12" # replaced through Maven resource filtering
  alias: "server"

paypal:
  base: "https://training-paypal-fake-api-mjf1rw.5sc6y6-2.usa-e2.cloudhub.io"
  responseTimeoutMillis: "2000"
